-- Add 20 more sample job listings, including some with 2026 deadlines

INSERT INTO public.job_listings (
    title, 
    company, 
    location, 
    job_type, 
    description, 
    requirements, 
    skills_required, 
    salary_min, 
    salary_max, 
    application_deadline
) VALUES 
(
    'Senior Software Engineer (Cloud)',
    'GlobalCloud Solutions',
    'Remote',
    'Full-time',
    'Lead the development of highly scalable, fault-tolerant cloud services. Design and implement new features, mentor junior engineers, and drive technical strategy.',
    ARRAY['8+ years of professional experience in software development', 'Expertise in cloud computing (AWS, Azure, or GCP)', 'Proven experience with microservices and distributed systems', 'Bachelor''s degree in Computer Science'],
    ARRAY['Python', 'Go', 'AWS', 'Kubernetes', 'Terraform', 'NoSQL'],
    130000,
    170000,
    '2025-05-30'
),
(
    'Product Marketing Manager',
    'InnovateCorp',
    'Boston, MA',
    'Full-time',
    'Develop and execute go-to-market strategies for our new suite of AI-powered products. Conduct market research, create compelling messaging, and collaborate with sales.',
    ARRAY['5+ years in Product Marketing for B2B tech products', 'Experience launching software products', 'Exceptional written and verbal communication skills', 'Bachelor''s degree in Marketing or Business'],
    ARRAY['Market Analysis', 'Go-to-Market Strategy', 'Content Creation', 'Sales Enablement', 'HubSpot'],
    95000,
    125000,
    '2025-04-15'
),
(
    'Cybersecurity Analyst Intern',
    'SecureNet Defense',
    'Washington, D.C.',
    'Internship',
    'Assist in monitoring security systems, responding to incidents, and conducting vulnerability assessments. Gain hands-on experience in a critical security environment.',
    ARRAY['Currently enrolled in Cybersecurity or Information Security program', 'Basic knowledge of network protocols and security principles', 'Interest in ethical hacking and threat analysis'],
    ARRAY['Wireshark', 'Kali Linux', 'SIEM', 'Network Security', 'Penetration Testing'],
    4800,
    6800,
    '2025-03-20'
),
(
    'Financial Analyst',
    'FinanceMax Group',
    'New York, NY',
    'Full-time',
    'Perform financial modeling, budgeting, and forecasting. Provide data-driven insights to senior management to support strategic decision-making and growth initiatives.',
    ARRAY['2-4 years of experience as a Financial Analyst', 'Proficiency in financial modeling and valuation techniques', 'CFA candidate or equivalent certification preferred', 'Advanced Excel skills'],
    ARRAY['Excel', 'Financial Modeling', 'SQL', 'Forecasting', 'SAP'],
    85000,
    110000,
    '2025-05-01'
),
(
    'Machine Learning Engineer',
    'DataFlow Analytics',
    'San Francisco, CA',
    'Full-time',
    'Design, build, and deploy machine learning models at scale. Work on projects involving natural language processing and computer vision.',
    ARRAY['Master''s degree in Computer Science or related field', '3+ years of experience building and deploying ML systems', 'Strong programming skills in Python', 'Deep understanding of ML algorithms'],
    ARRAY['Python', 'TensorFlow', 'PyTorch', 'AWS SageMaker', 'Docker', 'NLP'],
    120000,
    155000,
    '2025-06-01'
),
(
    'Cloud Architect',
    'TechCorp Inc.',
    'San Francisco, CA',
    'Full-time',
    'Architect and oversee the migration and deployment of applications to the public cloud. Ensure solutions are scalable, secure, and cost-effective.',
    ARRAY['10+ years in IT with 5+ years in cloud architecture', 'Certifications in at least one major cloud provider (e.g., AWS Solutions Architect)', 'Expertise in networking, security, and compliance in the cloud'],
    ARRAY['AWS', 'GCP', 'Azure', 'Kubernetes', 'Networking', 'Security'],
    150000,
    200000,
    '2025-04-20'
),
(
    'Full Stack Developer Intern',
    'StartupXYZ',
    'Austin, TX',
    'Internship',
    'Contribute to both the frontend and backend of our core platform. A great opportunity to become a versatile developer and work on features end-to-end.',
    ARRAY['Enrolled in a technical degree program', 'Basic knowledge of a modern web framework', 'Familiarity with database concepts', 'Eagerness to learn new technologies'],
    ARRAY['JavaScript', 'React', 'Node.js', 'PostgreSQL', 'HTML', 'CSS'],
    4000,
    6000,
    '2025-03-15'
),
(
    'Technical Writer',
    'CloudTech Solutions',
    'Remote',
    'Full-time',
    'Create clear, concise, and comprehensive technical documentation for our cloud APIs and developer tools. Work closely with engineering and product teams.',
    ARRAY['3+ years of technical writing experience for a software company', 'Ability to read and understand code snippets (e.g., JSON, Python)', 'Experience with documentation tools (e.g., GitBook, Sphinx)', 'Excellent command of English'],
    ARRAY['Documentation', 'API Reference', 'Git', 'Markdown', 'DITA'],
    75000,
    95000,
    '2025-05-15'
),
(
    'Biomedical Software Engineer',
    'HealthTech Innovators',
    'Cambridge, MA',
    'Full-time',
    'Develop software for medical devices and data analysis tools in a regulated environment. Ensure compliance with health standards and regulations.',
    ARRAY['Bachelor''s or Master''s in Biomedical Engineering or Computer Science', '3+ years of experience in software development', 'Familiarity with FDA/CE regulations for medical software', 'Experience with data processing algorithms'],
    ARRAY['C++', 'Python', 'MATLAB', 'Signal Processing', 'Medical Device Software'],
    90000,
    130000,
    '2025-06-30'
),
(
    'Game Developer Intern',
    'PixelPlay Studios',
    'Los Angeles, CA',
    'Internship',
    'Assist in programming game features, optimizing performance, and testing new mechanics for our upcoming mobile and console titles.',
    ARRAY['Pursuing a degree in Game Development or Computer Science', 'Portfolio of personal or student game projects', 'Basic knowledge of a major game engine (Unity or Unreal)'],
    ARRAY['C#', 'Unity', 'C++', 'Unreal Engine', 'Game Design'],
    3500,
    5500,
    '2025-11-10'
),
(
    '**Research Scientist, Quantum Computing**',
    '**QuantumLeap Labs**',
    '**Palo Alto, CA**',
    '**Full-time**',
    '**Join our groundbreaking research team to advance the state-of-the-art in quantum algorithms and hardware. Publish papers and present at major conferences.**',
    ARRAY['**Ph.D. in Physics, Computer Science, or related field**', '**5+ years of experience in quantum computing research**', '**Strong publication record**', '**Expertise in superconducting or trapped-ion systems**'],
    ARRAY['**Quantum Physics**', '**Qiskit**', '**Python**', '**C++**', '**Quantum Algorithms**'],
    160000,
    220000,
    '**2026-01-30**' -- Future Deadline 1 (2026)
),
(
    '**Aerospace Software Engineer**',
    '**SpaceDynamics Corp**',
    '**Houston, TX**',
    '**Full-time**',
    '**Develop mission-critical flight software for our next-generation orbital vehicles. Focus on robust, real-time embedded systems.**',
    ARRAY['**Master''s degree in Electrical or Aerospace Engineering**', '**5+ years experience with real-time operating systems (RTOS)**', '**Prior experience in the aerospace or defense industry is mandatory**'],
    ARRAY['**Ada**', '**C**', '**RTOS**', '**Embedded Systems**', '**Testing**'],
    110000,
    150000,
    '**2026-03-01**' -- Future Deadline 2 (2026)
),
(
    '**Associate Consultant**',
    '**Elite Strategy Group**',
    '**Chicago, IL**',
    '**Full-time**',
    '**Work on high-impact strategy projects for Fortune 500 clients. Conduct research, analyze data, and present recommendations to C-suite executives.**',
    ARRAY['**Graduating with a Bachelor''s or Master''s degree by Summer 2026**', '**Exceptional analytical and problem-solving abilities**', '**Proven leadership experience**', '**Ability to travel extensively**'],
    ARRAY['**Financial Analysis**', '**Market Research**', '**PowerPoint**', '**Communication**', '**Excel**'],
    90000,
    120000,
    '**2025-10-30**' -- Not 2026, but future-dated
),
(
    '**2026 Summer Analyst (Investment Banking)**',
    '**WallStreet Capital**',
    '**New York, NY**',
    '**Internship**',
    '**Participate in our rigorous 10-week summer program. Gain exposure to M&A, capital markets, and financial restructuring.**',
    ARRAY['**Undergraduate student graduating in Spring/Summer 2027**', '**Minimum 3.7 GPA**', '**Deep interest in finance and accounting**', '**Strong quantitative skills**'],
    ARRAY['**Financial Modeling**', '**Valuation**', '**Excel**', '**Bloomberg Terminal**'],
    12000,
    15000,
    '**2025-11-15**' -- Future Deadline 3 (Recruiting for 2026 summer)
),
(
    'Principal Data Scientist',
    'AI-Innovations',
    'Remote',
    'Full-time',
    'Set the technical direction for the entire Data Science organization. Lead complex, multi-functional projects from ideation to production deployment.',
    ARRAY['Ph.D. in a quantitative field (CS, Math, Statistics)', '10+ years of industry experience, with 3+ years as a Principal/Lead', 'Expertise in causal inference and experimentation', 'Fluency in MLOps best practices'],
    ARRAY['Python', 'Spark', 'Causal Inference', 'MLOps', 'AWS', 'Scala'],
    180000,
    250000,
    '2025-07-31'
),
(
    'Sales Development Representative (SDR)',
    'GrowthEngine Inc.',
    'Atlanta, GA',
    'Full-time',
    'Generate new business opportunities by conducting outbound prospecting, qualifying leads, and setting appointments for the sales team.',
    ARRAY['1-2 years of experience in a sales or customer-facing role', 'High energy and strong phone presence', 'Ability to meet and exceed monthly quotas', 'Bachelor''s degree'],
    ARRAY['Salesforce', 'Cold Calling', 'Lead Generation', 'Communication', 'B2B Sales'],
    50000,
    70000,
    '2025-04-10'
),
(
    '**Software Engineering Intern (Summer 2026)**',
    '**FutureTech Labs**',
    '**Seattle, WA**',
    '**Internship**',
    '**An exclusive internship for top-tier computer science students for the summer of 2026. Work on foundational platform infrastructure.**',
    ARRAY['**Currently enrolled in Computer Science program, graduating in 2027 or later**', '**Strong understanding of data structures and algorithms**', '**Experience in competitive programming is a plus**'],
    ARRAY['**C++**', '**Algorithms**', '**Operating Systems**', '**Distributed Systems**'],
    7000,
    9000,
    '**2026-02-15**' -- Future Deadline 4 (2026)
),
(
    '**Trainee Program: Supply Chain Logistics**',
    '**GlobalSupply Co.**',
    '**Dallas, TX**',
    '**Full-time**',
    '**A year-long rotational program for recent graduates, offering exposure to global logistics, procurement, and operations management.**',
    ARRAY['**Recent graduate (within 1 year) with a degree in Supply Chain or Engineering**', '**Excellent quantitative and analytical skills**', '**Willingness to travel internationally (up to 25%)**'],
    ARRAY['**Logistics**', '**SAP**', '**Data Analysis**', '**Supply Chain Management**'],
    65000,
    85000,
    '**2026-04-30**' -- Future Deadline 5 (2026)
),
(
    'DevOps Engineer II',
    'InfraTech Corp',
    'Denver, CO',
    'Full-time',
    'Maintain and scale our production environment. Focus on automation, reliability engineering, and continuous deployment improvements.',
    ARRAY['3+ years of experience in a DevOps or SRE role', 'Expert-level proficiency with Kubernetes and AWS', 'Experience with monitoring and logging tools (Prometheus, ELK)'],
    ARRAY['Kubernetes', 'AWS', 'Terraform', 'CI/CD', 'Prometheus', 'Python'],
    115000,
    140000,
    '2025-11-25'
),
(
    '**Resident Physician (R1)**',
    '**MegaHealth Hospital**',
    '**Los Angeles, CA**',
    '**Full-time**',
    '**First-year medical residency position in Internal Medicine. A rigorous clinical training program.**',
    ARRAY['**Completion of Medical School (MD or DO)**', '**Successful completion of USMLE/COMLEX exams**', '**Strong letters of recommendation**'],
    ARRAY['**Internal Medicine**', '**Patient Care**', '**Diagnosis**', '**Medical Knowledge**'],
    60000,
    75000,
    '**2025-12-31**' -- Future Deadline 6 (End of year)
);